version: "2"

services:
  magneticod:
    image: boramalper/magneticod:latest
    volumes:
      - ${MAGNETICOD_DATA}:/root/.local/share/magneticod
      - ${MAGNETICOD_CONFIG}:/root/.config/magneticod
    network_mode: "host"
    command:
      - "--indexer-addr=0.0.0.0:1212"
