name: Go

on: [ push, workflow_dispatch ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.21

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: |
        make magneticod

    - name: Test
      run: |
        make test

    - name: Check Formatting
      run: |
        make check-formatting
