name: Golang
on:
  - push
  - workflow_dispatch
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Golang
        uses: actions/setup-go@v2
        with:
          go-version: ^1.21
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y libsodium-dev libzmq3-dev libczmq-dev
      - name: Git Checkout
        uses: actions/checkout@v2
      - name: Go Build
        run: |
          go mod tidy
          cd src
          go build
